services:
    postgres:
        image: "postgres:latest"
        ports:
            - 6543:5432
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
